### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [1, 256, 256] at entry 0 and [3, 256, 256] at entry 7

### ISSUE THREAD

**Issue by gongmingbanzhi** [caoyunkang/CDO#14]
When I used my own dataset for training, an error occurred:
`2024-11-12 11:10:02.598 | INFO     | utils.training_utils:get_dir_from_args:69 - ===> Root dir for this experiment: ./result/hrnet32-SMUD-wi-OOM-wi-MOM/logger/grid
2024-11-12 11:10:32.384 | INFO     | datasets:get_dataloader_from_args:51 - ===> datasets: SMUD, class name/len: grid/557, batch size: 16
2024-11-12 11:11:39.892 | INFO     | datasets:get_dataloader_from_args:51 - ===> datasets: SMUD, class name/len: grid/2000, batch size: 16
CDO:grid:   0%|                                                                                                                                                      | 0/50 [01:11<?, ?it/s]
Traceback (most recent call last):
  File "/home/sxp/anomaly-detection/CDO-master/train.py", line 207, in <module>
    main(args)
  File "/home/sxp/anomaly-detection/CDO-master/train.py", line 130, in main
    metrics = test_epoch(model, test_dataloader, device, is_viz, img_dir,
  File "/home/sxp/anomaly-detection/CDO-master/train.py", line 39, in test_epoch
    for (data, mask, label, name) in dataloader:
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/sxp/anaconda3/envs/efficientad_env/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 256, 256] at entry 0 and [3, 256, 256] at entry 7`

**Comment by caoyunkang** [comment]
It appears that your images are in grayscale rather than RGB format. You can update the ``dataset`` file to ensure images are read in RGB format.
